#https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#JoinConfiguration
## NOTE: only in 1.14, due to a bug in kubeadm, this file is not used.
JoinConfiguration:
#  controlPlane:
#    localAPIEndpoint:
#      advertiseAddress: <your_address>
#      bindPort: 6443
  apiVersion: kubeadm.k8s.io/v1beta1
  # caCertPath: /etc/kubernetes/pki/ca.crt
  # discovery:
  #   bootstrapToken:
  #     apiServerEndpoint: 10.1.2.3:6443
  #     token: abcdef.0123456789abcdef
  #     unsafeSkipCAVerification: true
  #   timeout: 5m0s
  #   tlsBootstrapToken: abcdef.0123456789abcdef
  kind: JoinConfiguration
  # nodeRegistration:
  #   criSocket: /var/run/dockershim.sock
  #   name: <your_master_node_name>
