#
# Make (etcd) client certs available to masters
#
---

- name: Create cert dir for pki on master nodes
  file: "path=/etc/kubernetes/pki state=directory"

- name: Unarchive etcd certificate files on master nodes
  unarchive: "copy=yes src=/tmp/etcd-certs.tar.gz dest=/etc/kubernetes/pki"


