---
- name: kubectl aliases to ~/.{{ shell | default ('bash') }}rc
  lineinfile:
    dest: ~/.{{ shell | default ('bash') }}rc
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
  - "alias watch='watch ' "
  - "alias k='kubectl ' "
  - "alias kk='kubectl -o wide --show-labels '"
  - "alias ks='kubectl -n kube-system ' "
  - "alias kg='kubectl get --all-namespaces -o wide '" # --show-labels '"
  - "alias kgl='kubectl get --all-namespaces -o wide --show-labels '"
  - "alias kgp='kubectl get --all-namespaces -o wide --show-labels po'"
  - "alias wp='watch kg po '" # -w --show-labels '"
  - "alias wipt='watch -n1 iptables -vnL ' "

- name: Install optional packages like bash-completion
  package: name={{ item }} state={{ package_state | default ('latest') }}
  with_items:
  - bash-completion
  ignore_errors: yes

- name: add kubectl/kubeadm/helm shell competions to ~/.{{ shell | default ('bash') }}rc
  lineinfile:
    dest: ~/.{{ shell | default ('bash') }}rc
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
  - "# k8s shell completion; for zsh min vers is 5.2+"
  - "source <(kubectl completion {{ shell | default ('bash') }} 2>/dev/null || true)"
  - "source <(kubeadm completion {{ shell | default ('bash') }} 2>/dev/null || true)"
  - "source <(helm    completion {{ shell | default ('bash') }} 2>/dev/null || true)"
  