---
### ntpd:
- block:
  - name: ntpd and ntpdate | it is mandatory to have the time from all machines in sync
    package: state=present name={{ item }}
    environment: '{{ proxy_env | default ({}) }}'
    with_items:
    - ntp
    register: ntp_output
#    notify: # Debian & RH diff service name...
#    - Restart ntpd

  - name: ntpd configuration
    copy: content={{ntp_conf}} dest=/etc/ntp.conf backup=yes
    when: ntp_conf is defined
#    notify: # Debian & RH diff service name...
#    - Restart ntpd

  - name: Restart ntpd - RedHat/CentOS
    systemd: name=ntpd state=restarted enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Restart ntp - Debian
    systemd: name=ntp state=restarted enabled=yes
    when: ansible_os_family == "Debian"

  when: 
  - ntp_setup is defined
  - ntp_setup 
  - ntp_package is defined
  - ntp_package == "ntp"
  tags:
  - ntp
