---
- name: set hostname with fqdn
  hostname:
    name: "{{ inventory_hostname }}"
  when: set_hostname_to_inventory_hostname | default ( False )

- name: set hostname with fqdn - sol2
  shell: hostnamectl set-hostname {{ inventory_hostname }}
  when: set_hostname_to_inventory_hostname | default ( False )
  # This does not require restart (as per docs)

- name: create dir /var/log/journal (so node-problem-detector finds any issues with the nodes, should there be any)
  file:
    path: /var/log/journal
    state: directory
    mode: 0755

# Forcing restart of services
#- meta: flush_handlers
